Backend: SymbolicExpression
ClockPeriod: 5
ClockUncertainty: 12.5%
Compiler: vivado_hls
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
HLSIncludePath: /tools/Xilinx/Vitis_HLS/2023.1/include
HLSLibsPath: /tools/Xilinx/Vitis_HLS/2023.1/lnx64
IOType: io_parallel
InputData: null
NSymbols: 1
OutputDir: model_sym_template
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: d70a31a3
Version: 1.0.0
