Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    act1:
      Precision:
        param: auto
        result: auto
      Trace: false
    act2:
      Precision:
        param: auto
        result: auto
      Trace: false
    act3:
      Precision:
        param: auto
        result: auto
      Trace: false
    dense1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense1_linear:
      Precision:
        result: auto
      Trace: false
    dense2:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense2_linear:
      Precision:
        result: auto
      Trace: false
    dense3:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense3_linear:
      Precision:
        result: auto
      Trace: false
    x_in:
      Precision: ap_fixed<12, 4, AP_RND, AP_SAT>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_test/keras_model.keras'
OutputDir: model_test
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: model_test
Stamp: b05b8ebb
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
